title: Simon Grah
logo: "/images/logo.png?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist - Machine Learning Engineer 
  <br><br>
  <a href="https://www.linkedin.com/in/simon-grah-a91812147/">View My LinkedIn Profile</a>  
  <br><br>
  <a href="https://medium.com/@simon.grah">Medium Page</a>  

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
