title: Simon Grah
logo: "/images/logo.png?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist - Machine Learning Engineer 
  
  Hello, 
  My name is Simon Grah
  I have a background in applied mathematics with a specialization in data science, statistics and probability. 
  I started my career as a research data scientist at THALES. During almost 4 years, 
  I had the opportunity to work on both theoretical topics 
  (e.g. interpretability of machine learning, fairness, stream graph) as well as on applied cybersecurity 
  projects involving data science.  
  I then decided to join OCTO Technology and Accenture as a data science consultant. 
  This choice was driven by the desire to be more focused on the industrialization part of machine learning 
  and to work with different customers and business domains. 
  Therefore, in addition to ML modeling, I am more and more interested in MLOps, 
  software engineering craftsmanship and cloud engineering. 

  <br><br>
  <a href="https://www.linkedin.com/in/simon-grah-a91812147/">View My LinkedIn Profile</a>  
  <br><br>
  <a href="https://medium.com/@simon.grah">Medium Page</a>  

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
