title: Home
description: Simon's personal web page
author: Simon Grah
avatar: /images/logo.png
email: simon.grah.pro@gmail.com
skin: daylight

domain: sgrah-oss.github.io
url: https://sgrah-oss.github.io
# baseurl: /REPOSITORY-NAME/

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec
